### ISSUE TITLE
`changeScript` property not available

### ISSUE THREAD

**Issue by jaen** [tristanpemble/nix-nomad#2]
It seems that option to use custom reload script (cf. https://developer.hashicorp.com/nomad/docs/v1.3.x/job-specification/change_script) is missing. Would you consider regenerating the modules?

**Comment by jaen** [comment]
I added this as a draft PR so you can see what changed between what you had and 1.4.3: https://github.com/tristanpemble/nix-nomad/pull/3

**Comment by tristanpemble** [comment]
@jaen thanks for the contribution! I've merged #3. let me know if you need further help resolving the issue :)
