### ISSUE TITLE
Could you share me something about the scientific case. 

### ISSUE THREAD

**Issue by GTrunSec** [tristanpemble/nix-nomad#7]
Hi @tristanpemble , I learned from the readme that your company is exploring scenarios and applications related to data-science. Could you tell me something about that? I am looking for some real techniques/scenarios to bring the value of Nix to data-science into the real world. Actually, I only have a little work experience (working with a team)and can only gain inspiration from some valuable sharing(like you and the community).

#. My personal projects. 
- https://github.com/GTrunSec/DeSci/tree/main/nix (Build the scientific jobs with nix)
- https://github.com/GTrunSec/lambdaLake/tree/main/nix/vast (Build the DataLake with nix/nix-nomad)
- https://github.com/GTrunSec/desci-workflow-template (Integrate the dataflow/workflow with data-science)
  - https://github.com/GTrunSec/dataflow2nix/tree/main/nix/prefect   
- I'm currently trying to take lessons from a similar class  https://github.com/DataTalksClub/data-engineering-zoomcamp/tree/main  to help me nixify a dataLake infrastructure.

Another try: https://github.com/input-output-hk/marlowe-starter-kit/issues/1

Thanks

**Comment by tristanpemble** [comment]
hi @GTrunSec, Quartzy is a software company that builds a web app that life science researchers use.  I actually left that company a couple months ago. we weren't using Nix in any data science specific capacity, it was used entirely for devops and delivering that software to production infrastructure.

**Comment by GTrunSec** [comment]
thanks for your responding,  I see.
